#pragma once


#ifndef TOKENTYPE_H
#define TOKENTYPE_H

enum class TokenType {
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
	COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
	BANG, BANG_EQUAL,
	ASSIGN, EQUAL_EQUAL,
	MOD, MODASSIGN,
	GREATER, GREATER_EQUAL,
	PLUSPLUS,MINUSMINUS,
	MINUSASSIGN,PLUSASSIGN,STARASSIGN,DIVASSIGN,
	LESS, LESS_EQUAL,
	IDENTIFIER, STRING, NUMBER,
	LOGICAL_AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, LOGICAL_OR,
	PRINT, PRINTNL, RETURN, SUPER, THIS, TRUE, VAR, WHILE,
	END_OF_FILE, CALLABLE, INSTANCE, QUESTION_MARK, COLON, DO,
	BREAK, CONTINUE, NEW_LINE, READ
};

#endif
